[server]
headless = true
enableStaticServing = true

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"

[theme]
base = "light"
primaryColor = "#0d366b"
backgroundColor = "#f4f2ec"
secondaryBackgroundColor = "#ffffff"
textColor = "#141413"
borderColor = "#e2dfd6"

[theme.sidebar]
backgroundColor = "#0f2438"
secondaryBackgroundColor = "#1b3552"
textColor = "#ffffff"
primaryColor = "#cde2fb"
borderColor = "#2c4866"
